INCLUDE_PATH =  -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/contrib/library/game/game_core_lib/spec/include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL\include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/contrib/library/game/cpf_lib/spec/include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL_image\include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL_ttf\include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\OpenAL\include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/contrib/library/game/audio_snd_files_lib/spec/include" -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\libsndfile\include"
SHELL = /bin/sh
CC = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/gcc"
CPP = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/gcc"
CFLAGS = -O0 -pipe -imacros eif_config.mingw.h -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_UNICODE -DUNICODE  -DEIF_THREADS  -DEIF_IEEE_BEHAVIOR -DWORKBENCH -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/spec/windows/include" -I. $(INCLUDE_PATH)
CPPFLAGS = -O0 -pipe -imacros eif_config.mingw.h -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_UNICODE -DUNICODE  -DEIF_THREADS  -DWORKBENCH -I"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/spec/windows/include" -I. $(INCLUDE_PATH)
LDFLAGS = 
CCLDFLAGS =   -mwindows
LDSHAREDFLAGS =  
EIFLIB = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/spec/windows/lib/mingw/mtwkbench.a"
EIFTEMPLATES = C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/config/windows/templates
LIBS = 
MAKE = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/make.exe"
AR = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/ar"
LD = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/ld"
MKDEP =   --
MV = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/cp"
CP = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/cp"
RANLIB = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/ranlib.exe"
RM = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/rm" -f
FILE_EXIST = 
RMDIR = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/rd"
X2C = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/spec/windows/bin/x2c.exe"
SHAREDLINK = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/dllwrap"
SHAREDLIBS = -luser32 -lws2_32 -ladvapi32 -lgdi32 -lshell32 -lmsimg32 -lcomdlg32 -luuid -lole32 -loleaut32 -lcomctl32 -lmpr -lshlwapi -lwinspool -lstdc++ 
SHARED_SUFFIX = .dll
COMMAND_MAKEFILE = 
START_TEST = if [ ! -f finished ] ; then 
END_TEST = ; fi 
CREATE_TEST = "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/msys/1.0/bin/touch" finished
PATH := C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/libexec/gcc/mingw32/3.4.2;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Acer\Remote Files\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Git\cmd 
SYSTEM_IN_DYNAMIC_LIB = jeu.dll 

.SUFFIXES:.cpp .o 

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CPP) $(CPPFLAGS) -c $<

SUBDIRS = C1 C2 C3 E1

EXTERNALS =  \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\game_core_lib\spec\mingw\windows\lib\mtsdl_additions.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL\lib\windows\mingw\SDL.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL\lib\windows\mingw\SDLmain.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\cpf_lib\spec\mingw\windows\lib\mtcpf_additions.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL_image\lib\windows\mingw\SDL_image.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\SDL_ttf\lib\windows\mingw\SDL_ttf.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\OpenAL\libs\windows\mingw\OpenAL32.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\audio_snd_files_lib\spec\mingw\windows\lib\mtsndfile_additions.lib" \
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL\contrib\library\game\C_lib_win\libsndfile\lib\windows\mingw\libsndfile-1.lib"

all:: jeu.exe
	echo done > completed.eif

C1/Cobj1.o: Makefile E1/estructure.h
	cd C1 && $(START_TEST) $(MAKE) Cobj1.o $(END_TEST) && cd ..

C2/Cobj2.o: Makefile E1/estructure.h
	cd C2 && $(START_TEST) $(MAKE) Cobj2.o $(END_TEST) && cd ..

C3/Cobj3.o: Makefile E1/estructure.h
	cd C3 && $(START_TEST) $(MAKE) Cobj3.o $(END_TEST) && cd ..

E1/emain.o:  Makefile E1/Makefile
	$(CP) "$(EIFTEMPLATES)/emain.template" "E1/emain.c"
	cd E1 && $(START_TEST) $(MAKE) emain.o  $(END_TEST) && cd ..

E1/eoption.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) eoption.o  $(END_TEST) && cd ..

E1/epattern.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) epattern.o  $(END_TEST) && cd ..

E1/efrozen.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) efrozen.o  $(END_TEST) && cd ..

E1/ecall.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) ecall.o  $(END_TEST) && cd ..

E1/eplug.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) eplug.o  $(END_TEST) && cd ..

E1/eskelet.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) eskelet.o  $(END_TEST) && cd ..

E1/enames.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) enames.o  $(END_TEST) && cd ..

E1/evisib.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) evisib.o  $(END_TEST) && cd ..

E1/ececil.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) ececil.o  $(END_TEST) && cd ..

E1/einit.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) einit.o  $(END_TEST) && cd ..

E1/eparents.o : Makefile E1/Makefile E1/estructure.h
	cd E1 && $(START_TEST) $(MAKE) eparents.o  $(END_TEST) && cd ..

OBJECTS = E1/eparents.o  E1/einit.o  E1/ececil.o  E1/evisib.o  E1/enames.o  E1/eskelet.o  E1/eplug.o  E1/ecall.o  E1/efrozen.o  E1/epattern.o  E1/eoption.o  C3/Cobj3.o C2/Cobj2.o C1/Cobj1.o 

C_OBJECTS = C3/Cobj3.o C2/Cobj2.o C1/Cobj1.o 

EOBJECTS = E1/eparents.o  E1/einit.o  E1/ececil.o  E1/evisib.o  E1/enames.o  E1/eskelet.o  E1/eplug.o  E1/ecall.o  E1/efrozen.o  E1/epattern.o  E1/eoption.o  

PRECOMP_OBJECTS= "c:\users\sarah\documents\eiffel user files\14.05\precomp\spec\windows\EIFGENs\base-mt\W_code/mingw/precomp.lib"


jeu.exe: E1/emain.o $(OBJECTS) jeu.res 
	$(COMMAND_MAKEFILE)
	$(RM) $@
	$(CC) $(LDFLAGS) $(CCLDFLAGS) -o jeu.exe E1/emain.o $(PRECOMP_OBJECTS) jeu.res $(OBJECTS) $(EXTERNALS) $(EIFLIB) -luser32 -lws2_32 -ladvapi32 -lgdi32 -lshell32 -lmsimg32 -lcomdlg32 -luuid -lole32 -loleaut32 -lcomctl32 -lmpr -lshlwapi -lwinspool -lstdc++ $(ISE_SHAREDLIBS)

../../../jeu.rc:
	if [ ! -f ../../../jeu.rc ] ; then $(MV) "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/config/windows/mingw/eiffel.rc" ../../../jeu.rc ; fi 

jeu.res: ../../../jeu.rc Makefile
	"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/windres" --preprocessor='"C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/cpp.exe"' -I../../.. ../../../jeu.rc -O coff -o jeu.res

RCECIL = MTwmalloc.o MTwgarcol.o MTwlocal.o MTwexcept.o MTwstore.o \
	MTwretrieve.o MTwhash.o MTwtraverse.o MTwhashin.o MTwtools.o \
	MTwinternal.o MTwplug.o MTwcopy.o MTwequal.o MTwlmalloc.o MTwout.o \
	MTwtimer.o MTwurgent.o MTwsig.o MTwhector.o MTwcecil.o MTwbits.o \
	MTwfile.o MTwdir.o MTwmisc.o MTwerror.o MTwumain.o MTwmemory.o \
	MTwargv.o MTwboolstr.o MTwsearch.o MTwmain.o MTdebug.o MTinterp.o \
	MTwoption.o MTupdate.o MTwbench.o MTwrun_idr.o MTwcompress.o \
	MTwconsole.o MTwpath_name.o MTwobject_id.o MTweif_threads.o \
	MTwgen_conf.o MTweif_type_id.o MTwrout_obj.o MTweif_project.o \
	MTidrs.o MTwposix_threads.o MTnetwork.o mtipc.o MTwscoop.o \
	MTwmemory_analyzer.o MTwoffset.o 


#STATIC_CECIL PART
STATIC_CECIL = libjeu.o
cecil: $(STATIC_CECIL)
$(STATIC_CECIL): $(OBJECTS)
	$(AR) x $(EIFLIB)
	$(AR) rc $(STATIC_CECIL) $(OBJECTS) $(EXTERNALS) $(PRECOMP_OBJECTS) $(RCECIL)
	$(RANLIB) $(STATIC_CECIL)
	$(RM) $(RCECIL)



#SHARED_CECIL PART
SHARED_CECIL = libjeu$(SHARED_SUFFIX)
dynamic_cecil: $(SHARED_CECIL) 
DEF_FILE= c_jeu.def 
c_jeu.def: 
	$(RM) $@
	@echo LIBRARY libjeu.dll > $@
	@type "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/studio/config/windows/templates/cecil.def" >> $@

SHARED_CECIL_OBJECT = $(OBJECTS) \
		E1/emain.o
SHAREDFLAGS = $(LDSHAREDFLAGS) \
\
	--dlltool-name "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/dlltool" \
	--as "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/as" \
	--def $(DEF_FILE) --output-lib c_dll_jeu.lib -o $(SHARED_CECIL)

$(SHARED_CECIL): $(SHARED_CECIL_OBJECT)  $(DEF_FILE)
	if [ -f $(SHARED_CECIL) ] ; then $(RM) $(SHARED_CECIL) ; fi
	$(SHAREDLINK) $(SHAREDFLAGS) $(SHARED_CECIL_OBJECT) $(PRECOMP_OBJECTS) $(EXTERNALS) $(EIFLIB) $(SHAREDLIBS) 

#SYSTEM_IN_DYNAMIC_LIB PART

DEF_FILE= jeu.def
dynlib: $(SYSTEM_IN_DYNAMIC_LIB) 
E1/egc_dynlib.o: Makefile E1/Makefile
	$(CP) "$(EIFTEMPLATES)/egc_dynlib.template" E1/egc_dynlib.c
	cd E1 && $(MAKE) egc_dynlib.o && cd ..
E1/edynlib.o: Makefile E1/Makefile E1/edynlib.c 
	cd E1 && $(MAKE) edynlib.o && cd ..

SYSTEM_IN_DYNAMIC_LIB_OBJ = $(OBJECTS) \
		E1/edynlib.o E1/egc_dynlib.o 
DYNLIBSHAREDFLAGS = $(LDSHAREDFLAGS) \
\
	--dlltool-name "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/dlltool" \
	--as "C:\Program Files (x86)\Eiffel Software\EiffelStudio 14.05 GPL/gcc/windows/mingw/bin/as" \
	--def $(DEF_FILE) --output-lib dll_jeu.lib -o $(SYSTEM_IN_DYNAMIC_LIB)

$(SYSTEM_IN_DYNAMIC_LIB): $(SYSTEM_IN_DYNAMIC_LIB_OBJ)  $(DEF_FILE)
	if [ -f $(SYSTEM_IN_DYNAMIC_LIB) ] ; then $(RM) $(SYSTEM_IN_DYNAMIC_LIB) ; fi
	$(SHAREDLINK) $(DYNLIBSHAREDFLAGS) $(SYSTEM_IN_DYNAMIC_LIB_OBJ) $(PRECOMP_OBJECTS) $(EXTERNALS) $(EIFLIB) $(SHAREDLIBS) 



clean: sub_clean local_clean
clobber: sub_clobber local_clobber

local_clean::
	$(RM) core finished *.o *.so *.a

local_clobber:: local_clean
	$(RM) Makefile config.sh finish_freezing

sub_clean::
	for i in $(SUBDIRS); \
	do \
		if [ -r $$i/Makefile ]; then \
			(cd $$i ; $(MAKE) clean); \
		fi; \
	done

sub_clobber::
	for i in $(SUBDIRS); \
	do \
		if [ -r $$i/Makefile ]; then \
			(cd $$i ; $(MAKE) clobber); \
		fi; \
	done

